
version: '3.11'

services:
  bot:
    build: .
    environment:
      - API_ID=api_id
      - API_HASH=api_hash
      - BOT_TOKEN=token
      - DATABASE_URL = url



  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pwd"
    volumes:
      - .:/docker-entrypoint-initdb.db
    ports:
      - "5432:5432"
