
version: '3.11'

services:
  bot:
    build: .
    environment:
      - API_ID=22543134
      - API_HASH=c885f8546d67197050688eff7e499e70
      - BOT_TOKEN=6859624515:AAFXPT9BXueK80OB6Ggkyyd4EovFFDG39L4
      - DATABASE_URL = "postgresql://habrpguser:pgpwd4habr@postgres:5432/habrdb"



  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    volumes:
      - .:/docker-entrypoint-initdb.db
    ports:
      - "5432:5432"
